# Generated by Django 5.0.1 on 2024-02-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_tag_remove_note_category_rename_content_note_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
